version: "3.1"
services:
    azurednsproxy:
        build: .
        container_name: azurednsproxy
        restart: on-failure
        expose:
          - "53"
          - "53/udp"
        ports:
           - "53:53"
           - "53:53/udp"            