version: "3.1"
services:
    azurednsproxy:
        build: .
        container_name: azurednsproxy
        restart: on-failure
        expose:
          - "5353"
          - "5353/udp"
        ports:
           - "53:5353"
           - "53:5353/udp"            